// <auto-generated />
namespace VotingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_ids_in_motion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_ids_in_motion));
        
        string IMigrationMetadata.Id
        {
            get { return "201511122240365_user_ids_in_motion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
